# Generated by Django 6.0.3 on 2026-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
