# Generated by Django 6.0.3 on 2026-06-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_id_alter_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
